### PR TITLE
Feature image

### PR DESCRIPTION
**Pull request by Bhakti199**
Here I have created image component. It consist of responsive image and round image.

### CODE REVIEW

**Review by ShreyashMahajan — APPROVED** [review]
The code looks good and understandable.  Try to make it component library a little bit more responsive.

**Review by Namrata-J — APPROVED** [review]
the code looks good to go with merging!!

**Review by mariyasada — APPROVED** [review]
good to merge

**Comment by neetukumari4858** [comment]
overall looks good
-code is understandable.
-good naming convention.

**Review by neetukumari4858 — COMMENTED** [review]
overall looks good
-code is understandable.
-good naming convention.

**Pull request merged**
